#-------------------------------
# General Site Settings

menu:
- {name: 'Github',    url: 'www.github.com/wlpjames'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Solo',       
   company: 'Taqsim',                   
   thumb: 'thumbnail.png', 
   url: 'proj-1'}

- {name: 'Microtoner', 
   company: 'Taqsim',                   
   thumb: 'mocrotoner-ui.png', 
   url: 'proj-2'}

- {name: 'Fuego',      
   company: 'Sonic Nomad',              
   thumb: 'fuego-image.png', 
   url: 'proj-3'}

- {name: 'Connect',    
   company: 'Digitaize (C. Bechstein)', 
   thumb: 'digitaize-connect.png', 
   url: 'proj-4'}

#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'www.github.com/wlpjames'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/william-james-b06322162/'}
- {icon: 'envelope',  link: 'willjames@protonmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
